apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: store-backend
  template:
    metadata: 
      labels: 
        component: store-backend
    spec:
      containers:
        - name: store-backend
          image: 147379/k8s-micro-store-backend
          ports:
            - containerPort: 5002
          env:
            - name: MONGODB_HOST
              value: "mongodb-cluster-ip-service"
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
